<a href="https://colab.research.google.com/github/one-2730/ESAA-24-2/blob/Assignment/ESAA_24_2_week1_transcription.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1-3. 넘파이
주기능: 배열 기반의 연산, 데이터 핸들링   
기반 데이터 타임: ndarray(다차원 배열에 강점)   
ndarray   
데이터값: 숫자(int, unsigned int, float, complex), 문자열, 불 모두 가능   
*한 ndarray내의 데이터 타입은 동일해야 함   

In [1]:
import numpy as np

##Function & Method

**Function**   
- array() : 리스트 등의 인자를 ndarray로 변환

ndarray 생성   
- arange() : start부터 순차적으로 stop-1까지 생성 / 인자: start(default = 0), stop
- zeros() : 0으로 채워 생성 / 인자: ndarray shape
- ones() : 1로 채워 생성 / 인자: ndarray shape

**Method**   
- .shape : ndarray의 크기/ 튜플
- .ndim : ndarray의 차원
- .dtype : ndarray내의 데이터값 타입
- .astype : ndarray내의 데이터값 타입 변경
- .reshape : ndarray의 차원과 크기 변경


- .tolist : 리스트 자료형으로 변환

In [2]:
#array()
#.shape


array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) #1차원

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) #2차원

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
#.ndim

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
# .dtype

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [5]:
#서로 다른 데이터 타입을 가지는 리스트를 array()로 변환하면 데이터 크기가 가장 큰 데이터 타입으로 일괄 적용

list2 = [1, 2, 'test'] #int & string -> 유니코드 문자열 값으로 변환
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0] #int & float -> float64로 변환
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
#.astype()
# 대용량 데이터를 만드는 경우 데이터 타입 변경으로 메모리 절약 가능

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype) #float -> int 변경시 소수점 아래 삭제

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
#arange()

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape) #1차원

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
#zeros()
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

#ones()
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
#.reshape
#지정된 크기로 변경이 불가능하면 오류

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
#인자에 -1을 넣으면 호환 가능한 값으로 변경

array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [11]:
#reshape(-1, 1)로 ndarray들의 형태를 2차원이고 칼럼이 1개인 ndarray로 통일할 때 유용하게 사용

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원으로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


##Indexing 인덱싱


1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
2. **슬라이싱(Slicing)**: 연속된 인덱스 상의 ndarray를 추출하는 방식 'start:stop'으로 작성하면 start 인덱스에서 stop-1인 인덱스까지 반환
3. **팬시 인덱싱(Fancy Indexing)**: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
4. **불린 인덱싱(Boolean Indexing**): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환   

*index는 0부터 시작
*axis 0: 행(row) 방향 축
*axis 1: 열(column) 방향 축

###단일 값 추출

In [12]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print('array1:', array1)

value = array1[2] #3번째 index 위치의 데이터값
print('value:', value)
print(type(value)) #np.array내의 데이터값

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [13]:
#-기호를 이용하면 맨 뒤에서부터 추출

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두번째 값: 8


In [14]:
#단일 인덱스를 이용해 ndarray내의 데이터값 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [15]:
#다차원 ndarray에서 단일 값 추출

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


###슬라이싱

1. ':' 기호 앞에 시작 인덱스를 생략하면 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면 -1로 간주
3. ':' 기호 앞뒤로 인덱스를 생략하면 전체

In [16]:
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
array1 = np.arange(1, 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [18]:
#2차원 ndarray에서 슬라이싱

array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

#[행 방향 슬라이싱, 열 방향 슬라이싱]
print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[0:2, 0]\n', array2d[0:2, 0]) #슬라이싱과 단일 값 인덱스 동시에 사용 가능

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[0:2, 0]
 [1 4]


In [19]:
#2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원으로 반환

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


###팬시 인덱싱

In [20]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


###불린 인덱싱

**작동 방식**   
Step 1. array1d>5와 같이 ndarray의 필터링 조건을 [  ]안에 기재   
Step 2. False 값은 무시하고 True에 해당하는 인덱스값만 저장   
Step 3. 저장된 인덱스 데이터 세트로 ndarray 조회

In [21]:
array1d = np.arange(1, 10)
# [ ] 안에 array1d>5 Boolean Indexing 적용
array3 = array1d[array1d > 5]
print('array1d >  5 인덱싱 결과 값:', array3)

array1d >  5 인덱싱 결과 값: [6 7 8 9]


In [22]:
#ndarray 객체에 조건식을 할당하면 True/False로 이뤄진 ndarray 객체 반환 / 인덱싱에 적용하면 True 값만 반환

array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [23]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [24]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


##행렬의 정렬

Function    
- sort()
  - 반환되는 값: 정렬 행렬
  - 원본 행렬은 그대로
- argsort()
  - 원본 행렬 정렬시 기존 행렬의 원소에 대한 인덱스

Method   
- .sort()를 이용하는 방법
  - 반환되는 값: None
  - 원본 행렬을 직접 정렬

*기본적으로 오름차순, 내림차순 정렬은 [::-1] 적용

In [25]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 후 반환된 정렬 행렬: None
org_array.sort() 후 원본 행렬: [1 3 5 9]


In [26]:
#내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [27]:
#행렬이 2차원 이상인 경우 axis 축 값을 설정하여 행 방향 또는 열 방향으로 정렬
array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [28]:
#np.argsort()

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [29]:
#마찬가지로 [::-1]로 내림차순

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [30]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


##선형대수 연산

Function   
- dot(): 행렬 곱
- transpose(): 전치 행렬

In [31]:
#행렬 내적(행렬 곱)

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [32]:
#전치 행렬
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
